In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.2.1+cu121


# #Introduction to tensors
creating Tensors

In [ ]:
# Scalar

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
#Vector

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

In [ ]:
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor= torch.tensor([[[1,2,3],
                      [2,4,5],
                      [5,6,7]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [2, 4, 5],
         [5, 6, 7]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

##Random Tensors




In [ ]:
random_tensor=torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.2578, 0.0478, 0.3900, 0.2998],
        [0.2182, 0.3396, 0.1268, 0.6281],
        [0.3435, 0.8571, 0.4987, 0.9234]])

In [ ]:
torch.rand(3,3)

tensor([[0.5188, 0.1975, 0.6706],
        [0.6203, 0.5428, 0.3141],
        [0.5948, 0.2939, 0.2979]])

In [ ]:
zeros=torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.range(0,10)

<ipython-input-34-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 ten_zeros=torch.zeros_like(input=one_to_ten)
 ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Manipulating Tensors

#Addition
#Subtraction
#Multiplication(element wise)
#Division
#Matrix Multiplication


In [ ]:
tensor=torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# Matrix multiplication
#Inner dimesnsions must match:
#(3,2) @ (3,2)-- Wont Work
#(3,2) @ (2,3)-- Will work
#(2,3) @ (3,2)-- Will work


In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.1046, 0.9271],
        [0.7011, 0.5665]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2199, 0.3554, 0.2704],
        [0.8389, 0.9315, 0.8386],
        [0.4426, 0.8429, 0.6023]])

In [ ]:
# Tensor Aggregation(max,min,sum,mean etc)

In [ ]:
# Create a tensor
x=torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
# Find the max
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Find the Sum
torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

In [ ]:
# Finding the positional min & max

x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
# Reshaping

In [ ]:
# Lets create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze()- removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])