In [ ]:
import torch
import numpy as np

# 1. Write a python program to create a tensor of shape (3,3) filled with random numbers between 0 and 1.

In [ ]:
tensor = torch.rand(3,3)
print('Random Tensor:',tensor)

Random Tensor: tensor([[0.1213, 0.5527, 0.5623],
        [0.4636, 0.2808, 0.5818],
        [0.7535, 0.9613, 0.1105]])


In [ ]:
arr = np.random.rand(3,3)
print('Random Array:',arr)

Random Array: [[0.33842738 0.04839704 0.63686517]
 [0.10091935 0.62168972 0.82790599]
 [0.18237168 0.29280641 0.24277036]]


In [ ]:
import torch

A = torch.rand(3, 3)
B = torch.rand(3, 3)
print("Tensor A:", A)
print("Tensor B:", B)

Tensor A: tensor([[0.4830, 0.0637, 0.3044],
        [0.5150, 0.3008, 0.3791],
        [0.2878, 0.4327, 0.2772]])
Tensor B: tensor([[0.2059, 0.8529, 0.1998],
        [0.3073, 0.4773, 0.1438],
        [0.8374, 0.3653, 0.4207]])


# 2. Perform basic tensor operations including matrix addition, multiplication, and transpose.

# Addition

In [ ]:
add_result = A+B
print('Addition:',add_result)

Addition: tensor([[0.6890, 0.9167, 0.5042],
        [0.8223, 0.7781, 0.5229],
        [1.1253, 0.7981, 0.6980]])


# Multiply

In [ ]:
mul_result = torch.matmul(A,B)
print('Multiply:',mul_result)

Multiply: tensor([[0.3739, 0.5536, 0.2337],
        [0.5160, 0.7213, 0.3056],
        [0.4244, 0.5533, 0.2364]])


# Transpose

In [ ]:
transpose_A = A.T
print('Transpose:',transpose_A)

Transpose: tensor([[0.4830, 0.5150, 0.2878],
        [0.0637, 0.3008, 0.4327],
        [0.3044, 0.3791, 0.2772]])


# 3. Convert the resulting tensor into a Numpy array and then reshape it into a (1,9) tensor.

In [ ]:
import torch
A = torch.rand(3,3)
B = torch.rand(3,3)

print('Tensor:',A)
print('Tensor:',B)

Tensor: tensor([[0.9755, 0.9957, 0.1416],
        [0.2789, 0.4931, 0.5065],
        [0.0842, 0.3306, 0.6950]])
Tensor: tensor([[0.1517, 0.2973, 0.8165],
        [0.0864, 0.6607, 0.4733],
        [0.1913, 0.7550, 0.7108]])


In [ ]:
C = A + B
print('Result Addition:',A)

Result Addition: tensor([[0.9755, 0.9957, 0.1416],
        [0.2789, 0.4931, 0.5065],
        [0.0842, 0.3306, 0.6950]])


In [ ]:

C_numpy = C.numpy()
print('Converted to NumPy Array:',C_numpy)

Converted to NumPy Array: [[1.1272628  1.2929547  0.9581081 ]
 [0.36530095 1.1537533  0.97988534]
 [0.27548546 1.0856938  1.4057498 ]]


In [ ]:
C_reshaped = C_numpy.reshape(1, 9)
print('Reshaped NumPy Array:',C_reshaped)

Reshaped NumPy Array: [[1.1272628  1.2929547  0.9581081  0.36530095 1.1537533  0.97988534
  0.27548546 1.0856938  1.4057498 ]]
